# Generated by Django 4.1.5 on 2023-02-04 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_alter_gaschek_device_alarm_alter_gaschek_device_call_and_more'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('gas_dealer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='accounts.gas_dealer')),
                ('payment_for', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='orders.cylinder_price')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
