# Generated by Django 4.1.7 on 2023-09-23 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_gaschek_device_alarm_alter_gaschek_device_call_and_more'),
        ('payment', '0002_payment_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cylinder_price'),
        ),
    ]
