# Generated by Django 4.1.5 on 2023-01-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='usernames',
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True),
        ),
    ]
