# Generated by Django 5.0.2 on 2024-02-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_delete_gaschek_device"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="verified_email",
        ),
    ]
