# Generated by Django 5.0.7 on 2024-08-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_verified_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="otp",
            field=models.IntegerField(),
        ),
    ]
