# Generated by Django 4.1.5 on 2023-02-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas_dealer',
            name='account_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
