# Generated by Django 4.1.5 on 2023-02-04 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_gas_dealer_account_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['usernames']},
        ),
        migrations.CreateModel(
            name='Gaschek_Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm', models.CharField(choices=[
                 ('on', 'on'), ('off', 'off')], default='off', max_length=10)),
                ('call', models.CharField(choices=[
                 ('on', 'on'), ('off', 'off')], default='off', max_length=10)),
                ('text', models.CharField(choices=[
                 ('on', 'on'), ('off', 'off')], default='off', max_length=10)),
                ('cylinder', models.CharField(default='0kg', max_length=10)),
                ('gas_mass', models.FloatField(default='0kg', max_length=10)),
                ('gas_level', models.IntegerField(default=0)),
                ('battery_level', models.IntegerField(default=0)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
