# Generated by Django 4.1.5 on 2023-02-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_gaschek_device_alarm_alter_gaschek_device_call_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaschek_device',
            name='alarm',
            field=models.CharField(
                choices=[('on', 'on'), ('off', 'off')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='gaschek_device',
            name='call',
            field=models.CharField(
                choices=[('on', 'on'), ('off', 'off')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='gaschek_device',
            name='text',
            field=models.CharField(
                choices=[('on', 'on'), ('off', 'off')], default='off', max_length=10),
        ),
    ]
