# Generated by Django 4.1.5 on 2023-03-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_country_code_alter_gas_dealer_selling_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gas_dealer',
            old_name='location',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='gas_dealer',
            name='bank',
            field=models.CharField(choices=[('off', 'off'), ('on', 'on')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gas_dealer',
            name='longitude',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gas_dealer',
            name='percentage_charge',
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gas_dealer',
            name='subaccount_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gas_dealer',
            name='subaccount_id',
            field=models.BigIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gaschek_device',
            name='alarm',
            field=models.CharField(choices=[('off', 'off'), ('on', 'on')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='gaschek_device',
            name='call',
            field=models.CharField(choices=[('off', 'off'), ('on', 'on')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='gaschek_device',
            name='text',
            field=models.CharField(choices=[('off', 'off'), ('on', 'on')], default='off', max_length=10),
        ),
    ]
