# Generated by Django 4.1.5 on 2023-03-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_gas_dealer_bank_gas_dealer_bank_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abandoned_Subaccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('subaccount_code', models.CharField(blank=True, max_length=100)),
                ('subaccount_id', models.BigIntegerField(blank=True)),
            ],
        ),
    ]
