# Generated by Django 4.1.5 on 2023-03-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_gas_dealer_is_verified_alter_gaschek_device_alarm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gas_dealer',
            name='rating',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='gas_dealer',
            name='users_rate_count',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='gas_dealer',
            name='users_rate_cummulation',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='gaschek_device',
            name='alarm',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='gaschek_device',
            name='call',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='gaschek_device',
            name='text',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=10),
        ),
    ]
