# Generated by Django 4.1.5 on 2023-03-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_gas_dealer_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gas_dealer',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
    ]
