# Generated by Django 4.1.7 on 2023-07-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_gaschek_device_alarm_alter_gaschek_device_call_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaschek_device',
            name='alarm',
            field=models.CharField(choices=[('off', 'off'), ('on', 'on')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='gaschek_device',
            name='call',
            field=models.CharField(choices=[('off', 'off'), ('on', 'on')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='gaschek_device',
            name='text',
            field=models.CharField(choices=[('off', 'off'), ('on', 'on')], default='off', max_length=10),
        ),
    ]
