# Generated by Django 4.1.7 on 2023-09-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_gaschek_device_indicator_alter_gaschek_device_alarm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('gas_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gas_dealer')),
            ],
        ),
        migrations.CreateModel(
            name='Cylinder_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder', models.DecimalField(decimal_places=1, max_digits=10)),
                ('price', models.IntegerField()),
                ('gas_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gas_dealer')),
            ],
            options={
                'ordering': ['gas_dealer'],
            },
        ),
    ]
