# Generated by Django 4.1.5 on 2023-02-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_gaschek_device_alarm_alter_gaschek_device_call_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas_Leakage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('gaschek_device', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='accounts.gaschek_device')),
            ],
        ),
    ]
