# Generated by Django 4.1.5 on 2023-02-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp32', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas_leakage',
            name='action',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
