# Generated by Django 5.0.2 on 2024-02-15 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaschek_device',
            name='alarm',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='gaschek_device',
            name='call',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='gaschek_device',
            name='indicator',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='gaschek_device',
            name='text',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='gaschek_device',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
