# Generated by Django 5.0.2 on 2024-02-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_alter_gaschek_device_cylinder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaschek_device',
            name='device_update_time',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='gaschek_device',
            name='alarm',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='gaschek_device',
            name='call',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='gaschek_device',
            name='indicator',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='gaschek_device',
            name='text',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=10),
        ),
    ]
