# Generated by Django 4.1.5 on 2023-02-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas_orders',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
