# Generated by Django 4.1.5 on 2023-02-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_gas_orders_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder_price',
            name='cylinder',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
