# Generated by Django 4.1.5 on 2023-02-12 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_gaschek_device_alarm_alter_gaschek_device_call_and_more'),
        ('orders', '0003_alter_cylinder_price_cylinder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('gas_dealer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='accounts.gas_dealer')),
            ],
        ),
    ]
