# Generated by Django 4.1.5 on 2023-03-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_gas_orders_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gas_orders',
            old_name='confirmed',
            new_name='dealer_confirmed',
        ),
        migrations.AddField(
            model_name='gas_orders',
            name='user_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
