# Generated by Django 4.1.7 on 2023-09-23 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_payment_for'),
        ('orders', '0006_rename_confirmed_gas_orders_dealer_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_fee',
            name='gas_dealer',
        ),
        migrations.RemoveField(
            model_name='gas_orders',
            name='reference',
        ),
        migrations.AddField(
            model_name='gas_orders',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.payment'),
        ),
        migrations.DeleteModel(
            name='Cylinder_Price',
        ),
        migrations.DeleteModel(
            name='Delivery_Fee',
        ),
    ]
